name:                sepo
version:             0.1.0.0
github:              "CoderPuppy/sepo"
license:             BSD3
author:              "CoderPuppy"
maintainer:          "coderpup@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CoderPuppy/sepo#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2 && < 1.3
- containers >= 0.6 && < 0.7
- time >= 1.8 && < 1.9
- megaparsec >= 7.0 && < 7.1

ghc-options:
- -Wno-tabs

default-extensions:
- OverloadedStrings
- DataKinds
- TypeOperators
- LambdaCase
- RecordWildCards
- TupleSections
- DerivingStrategies
- DeriveFunctor

library:
  source-dirs: src
  dependencies:
  - servant >= 0.15 && < 0.16
  - servant-client >= 0.15 && < 0.16
  - aeson >= 1.4 && < 1.5
  - http-client >= 0.5 && < 0.6
  - http-client-tls >= 0.3 && < 0.4
  - http-api-data >= 0.4 && < 0.5
  - http-types >= 0.12 && < 0.13
  - dbus >= 1.2 && < 1.3
  - split >= 0.2 && < 0.3
  - async >= 2.2 && < 2.3
  - base64-bytestring >= 1.0 && < 1.1

executables:
  sepo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sepo

tests:
  sepo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sepo
